SELECT a.region, a.year, a.week,
downlink_avg_thp_700, downlink_avg_thp_1800, downlink_avg_thp_2600, downlink_avg_thp_total, uplink_avg_thp_700,uplink_avg_thp_1800, uplink_avg_thp_2600, uplink_avg_thp_total,
average_user_volume_700,average_user_volume_1800, average_user_volume_2600, average_user_volume_total average_user_volume_lte


FROM

(SELECT distinct date_part('year'::text, main_kpis_lte_daily.date) AS year,
    date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval) AS week,
    cells.region,
    round(COALESCE(sum(main_kpis_lte_daily.cell_downlink_avg_thp_num) FILTER (WHERE frequency=700) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_downlink_avg_thp_den) FILTER (WHERE frequency=700) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS downlink_avg_thp_700,
    round(COALESCE(sum(main_kpis_lte_daily.cell_uplink_avg_thp_num) FILTER (WHERE frequency=700) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_uplink_avg_thp_den) FILTER (WHERE frequency=700) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS uplink_avg_thp_700,
    sum(main_kpis_lte_daily.average_user_volume) FILTER (WHERE frequency=700) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) AS average_user_volume_700,
    round(COALESCE(sum(main_kpis_lte_daily.cell_downlink_avg_thp_num) FILTER (WHERE frequency=1800) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_downlink_avg_thp_den) FILTER (WHERE frequency=1800) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS downlink_avg_thp_1800,
    round(COALESCE(sum(main_kpis_lte_daily.cell_uplink_avg_thp_num) FILTER (WHERE frequency=1800) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_uplink_avg_thp_den) FILTER (WHERE frequency=1800) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS uplink_avg_thp_1800,
    sum(main_kpis_lte_daily.average_user_volume) FILTER (WHERE frequency=1800) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) AS average_user_volume_1800,
	round(COALESCE(sum(main_kpis_lte_daily.cell_downlink_avg_thp_num) FILTER (WHERE frequency=2600) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_downlink_avg_thp_den) FILTER (WHERE frequency=2600) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS downlink_avg_thp_2600,
    round(COALESCE(sum(main_kpis_lte_daily.cell_uplink_avg_thp_num) FILTER (WHERE frequency=2600) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_uplink_avg_thp_den) FILTER (WHERE frequency=2600) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS uplink_avg_thp_2600,
    sum(main_kpis_lte_daily.average_user_volume) FILTER (WHERE frequency=2600) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) AS average_user_volume_2600,
    round(COALESCE(sum(main_kpis_lte_daily.cell_downlink_avg_thp_num) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_downlink_avg_thp_den) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS downlink_avg_thp_total,
    round(COALESCE(sum(main_kpis_lte_daily.cell_uplink_avg_thp_num) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) / NULLIF(sum(main_kpis_lte_daily.cell_uplink_avg_thp_den) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region), 0::real), 1::real)::numeric, 2) AS uplink_avg_thp_total,
    sum(main_kpis_lte_daily.average_user_volume) over (partition by date_part('week'::text, main_kpis_lte_daily.date + '1 day'::interval), date_part('year'::text, main_kpis_lte_daily.date), cells.region) AS average_user_volume_total
   FROM lte_kpi.main_kpis_lte_daily
     JOIN lte_control.cells ON main_kpis_lte_daily.enodeb = cells.site AND main_kpis_lte_daily.locellid = cells.cellid

     where date = '2017-07-30') a